### ISSUE TITLE
support environment variables

### ISSUE THREAD

**Issue by trondhindenes** [honeycombio/honeyaws#69]
api key should be configurable using environment variables. There's a PR from 2017 that seems to implement this, but it was never merged. That is unfortunate.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
