### ISSUE TITLE
parser error

### ISSUE THREAD

**Issue by trondhindenes** [honeycombio/honeyaws#70]
Looks like honeyaws doesnt correctly deal with all possible permutations of aws logs:
`time="2020-03-25T14:00:19Z" level=error msg="Couldn't parse request" error="parse \"http://my-lb.eu-central-1.elb.amazonaws.com:443-\": invalid port \":443-\" after host"`

colon-port is afaik a valid way of specifying the port and altho this log line indicates something wrong on our end, imho honeycomb should still be able to parse the data.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
